### ISSUE TITLE
Missing '---' in Readme

### ISSUE THREAD

**Issue by Latrasis** [SparkartGroupInc/gulp-markdown-to-json#4]
Was stuck for 1hour trying to figure out what was wrong until figured out the the example given has the "---" missing. It's silly i know.

**Comment by Pirhoo** [comment]
I suppose @Latrasis is talking about the opening `---`, like so:

```markdown
---
slug: bushwick-artisan
title: Wes Anderson pop-up Bushwick artisan
layout: centered
---

## YOLO
Chia quinoa meh, you probably haven't heard of them sartorial Holowaychuk pickled post-ironic. Plaid ugh vegan, Sixpoint 8-bit sartorial artisan semiotics put a bird on it Mission bicycle rights Club-Mate vinyl.
```

I got the same issue :)

**Comment by pushred** [comment]
Ahhhh. I was new to frontmatter myself so this detail was escaping me! Thanks so much for pointing this out guys, and sorry for the trouble.
